name: Web Scraping Job

on:
  workflow_dispatch:

jobs:
  scrape_website:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
          sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget -N https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install -r requirements.txt
          
      - name: Run web scraping script
        run: python3 scrape.py

      - name: commit files
        run: |
          git config --local user.email "kshtiijroodkee1@gmail.com"
          git config --local user.name "horizenight"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
              
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 