name: Web Scraping Job

on:
  workflow_dispatch:

jobs:
  scrape_website:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install -r requirements.txt
          
      - name: Run web scraping script
        run: python3 scrape.py

      - name: commit files
        run: |
          git config --local user.email "kshtiijroodkee1@gmail.com"
          git config --local user.name "horizenight"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
              
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 